### ISSUE TITLE
PDF Q-Pulse docs don't match actual docs

### ISSUE THREAD

**Issue by mattdmem** [sch-sdgs/SDGSCompetence#11]
![DB comp doc](https://user-images.githubusercontent.com/16154750/68113473-ca851600-feeb-11e9-932d-27d17d1e44f4.png)
[UV evaluation (1).pdf](https://github.com/sch-sdgs/SDGSCompetence/files/3803477/UV.evaluation.1.pdf)

Sorry found another odd thing re the pdf,
 
The associated qpulse documents listed in the pdf do not match those listed in the database, see pdf and screenshot of the same competence. I can see this in other documents too.

**Comment by lsollars** [comment]
Fixed in develop_lizzy
