### ISSUE TITLE
multiple issues - competence showing 500 error

### ISSUE THREAD

**Issue by mattdmem** [sch-sdgs/SDGSCompetence#14]
Hello
 
I keep getting the attached error when  trying to view the “Analysis – Constitutional Blood analysis competence” from my Dashboard,
 
And also when I view the Osteogenesis competence that have activated, I continue to submit evidence and get same error message.
 
I also have two competences from Joanne Brock that I need to reject as there’s no evidence attached, but when I reject and make a comment I get the second message (screenshot2).
 
Ta
 
Duncan
 
![screenshot](https://user-images.githubusercontent.com/16154750/68474648-e9eaae80-021d-11ea-902f-de43df4dc3ff.png)

**Comment by lsollars** [comment]
think these have all been fixed in develop_lizzy and tested on Duncan's login
