### ISSUE TITLE
Make Management overview page for Service

### ISSUE THREAD

**Issue by lsollars** [sch-sdgs/SDGSCompetence#33]
At the moment, users can only see details of people who they line manage. Head of Oncology would like to see details for whole Oncology team, and not just who has expired like in Reports page

Can we make something like a Management overview page? For members of SMG. Or give them access to everyone in their service for example rather than just line managees?

**Comment by Istaisa** [comment]
Have put down foundations for this - code on dev_naomi_service_overview

- added new module (mod_hos) which contains the service overview page (functionally the same as the line manager overview)
- added new head of service permission
- updated base HTML so correct head of service page conditionally appears to those with permissions
- updated viewing/adding/editing a service so head of service is included
- updated models and database

Minor bits (eg. JS for autocompleting names) is ongoing.

**Comment by Istaisa** [comment]
Updated so JS works

**Comment by Istaisa** [comment]
Released in v1.0.0
