### ISSUE TITLE
Needs a complete overhaul of Reports page

### ISSUE THREAD

**Issue by lsollars** [sch-sdgs/SDGSCompetence#34]
The donuts are not useful. List of requirements from Duncan:

What I’d like to be able to do is for a set period of time e.g. 1 month or 1 year ask:
•	How many competences completed?
•	How many competences expired/overdue?
•	How many competences activated?
•	How many competences activated but not completed after 3 months? (may not be doable but would be nice)
•	How many reassessments done? (the 1 year style reassessment).
•	How many competences reached 4 year expiry?
•	Spit into lab services, oncology, constitutional, bioinformatics (though bioinformatics maybe better lumped into constitutional).

Could this sort of info be presented graphically? But also allow us to dig into it more and identify individuals who haven’t completed competences etc?

**Comment by mattdmem** [comment]
can't believe you don't think my donuts are not useful :(

**Comment by lsollars** [comment]
I love the donuts.... but aside from them making me want to eat doughnuts, I think management want more tracking over time sorta things :(

**Comment by lsollars** [comment]
now line graphs, monitoring over time
