### ISSUE TITLE
If multiple files are selected for upload, only one is actually uploaded

### ISSUE THREAD

**Issue by lsollars** [sch-sdgs/SDGSCompetence#41]
If multiple files are selected in the evidence upload, it doesn't loop through them and attach them all, only one of them (assuming the last or first one), Weirdly, when the signer-offer gets the evidence, they see all the filenames, but when opening each file it will be the same file underneath.

Probably just needs some kind of loop to attach each piece of evidence, or at least a warning saying only one doc can be uploaded at a time.

**Comment by Istaisa** [comment]
Updated - works for files tested.
Also fixed issue where files were uploading empty (bug may not be present in live environment)

**Comment by Istaisa** [comment]
Released in v1.0.0
