### ISSUE TITLE
Put catch in for evidence not attached to subsections

### ISSUE THREAD

**Issue by lsollars** [sch-sdgs/SDGSCompetence#52]
If user doesn't select any subsections for evidence they can proceed without it linking the evidence to any assessments. This then breaks the signer-offers dashboard. 

Needs a catch, something like "you haven't selected any subsections" type of warning message.

**Comment by Istaisa** [comment]
Fixed in dev_naomi

Now returns the page with an error message explaining one or more active subsection must be selected.

This also catches another bug where the page errored if you tried to upload evidence for inactive subsections.
