### ISSUE TITLE
Email when competencies have expired or are expiring

### ISSUE THREAD

**Issue by lsollars** [sch-sdgs/SDGSCompetence#59]
Needs a cron job daily to see when competencies have reached expiry or when 7 days to go or something. To warn people ahead of time.

**Comment by Istaisa** [comment]
Email job:

- flags for year expired competencies as 'Four Year Due'
- Emails users when competencies are 30, 7 and 0 days from four year expiry
- Emails users when competencies are 30, 7 and 0 days from expiry.

Implemented in dev_naomi.
